version: "3.8"
services:
  challenge_postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:25432:5432
    env_file: .env
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
